### ISSUE TITLE
`RecordItems` iterator stops on mismatching record type

### ISSUE THREAD

**Issue by stbuehler** [mikedilger/resolv-rs#1]
All sections can carry records of different type; the iterator should skip all records with different type.

Right now it returns `None` (through the `.ok()` call at the end), which is the "universal" stop signal for iterators.

The most important case for this is when iterating over the answer section which contains a CNAME (usually as the first record in the section).

The iterator should also either returns the parse errors (after skipping the records with different type) or skip broken records; returning `None` is again not a good option.

**Comment by mikedilger** [comment]
Thanks for finding this.  By way of explanation, I coded this library for a project that a client cancelled, so it may not have much real world exposure yet, hence bugs like this.

Can you check if the code on the 'fix1' branch fixes this for you?  I don't easily have access to the situation you describe. Thanks.

**Comment by stbuehler** [comment]
I'll try to test it later, but it looks good so far regarding my original issue.  Small nit: if the lower level parse error should lead to aborting the sequence you might want to set index to len before returning `None`.

**Comment by stbuehler** [comment]
I can confirm it fixes the issue.  If you want to try yourself, query e.g. for `mail.google.com` - for me this returns this in the answer section (i.e. mixed types):

```
mail.google.com.	430062	IN	CNAME	googlemail.l.google.com.
googlemail.l.google.com. 128	IN	A	172.217.22.37
```

**Comment by mikedilger** [comment]
I just updated to 0.1.4 and published.

**Comment by stbuehler** [comment]
Thanks for fixing, and thanks for providing the crate in the first place.

I decided to roll my own iterator anyway (because I really wanted "proper" error handling), and build an `AddressRecord` trait on top of `RecordData`. See https://github.com/stbuehler/rust-alookup/blob/master/src/resolv_ext.rs if you're interested.
