### ISSUE TITLE
Problems during linking stage

### ISSUE THREAD

**Issue by frenkel** [mikedilger/resolv-rs#5]
First of al: thanks for creating this crate! I've been using it for a while now and I really like it.

Yesterday I upgraded my workstation to Fedora 35 and now I can't finish the linking stage of https://github.com/frenkel/timer-for-harvest anymore. This is the error I receive:

```
  = note: /usr/bin/ld: /home/frank/Source/rust/timer-for-harvest/target/debug/deps/libresolv-751f8392f81ccefb.rlib(resolv-751f8392f81ccefb.resolv.2248902c-cgu.3.rcgu.o): in function `resolv::Resolver::query':
          /home/frank/.cargo/registry/src/github.com-1ecc6299db9ec823/resolv-0.2.0/src/lib.rs:195: undefined reference to `__res_nquery'
          collect2: error: ld returned 1 exit status
          
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

```

This looks like a missing library to me, but I believe this is part of glibc which is installed (including glibc-devel). Any thoughts on how to fix this?

**Comment by mikedilger** [comment]
Hi, thanks for the positive feedback!

The library is normally called 'resolv'.  If you look in libresolv-sys/build.rs you'll see the "-l resolv" statement (usually /usr/lib/libresolv.so.2)

libresolv-sys was generated with rust-bindgen quite a while back and things may have changed, so it is possible that they need to be regenerated and code slightly modified if libresolv changed (e.g. if the new fedora has a libresolv.so.3, please let me know).

**Comment by frenkel** [comment]
Thanks for looking into this! Yes, libresolv is available on the system with the same major version, so that doesn't seem to be the problem:

```
/usr/lib64/libresolv.so
/usr/lib64/libresolv.so.2
```

`"-lresolv"` is also shown in the linking command that fails to find the `__res_nquery` symbol.
Any other ideas how to debug this?

**Comment by frenkel** [comment]
Reported this upstream and got the following response: https://bugzilla.redhat.com/show_bug.cgi?id=2005241#c1

How would I go about regenerating this with bindgen?

**Comment by mikedilger** [comment]
Ok. I made a branch called glibc233 where I regenerated against my current system which has glibc 2.33.  I don't have 2.34 yet but since ArchLinux tends to be bleeding edge I might get it next time I upgrade.   I also updated the README on that branch to explain how you can regenerate against your glibc.

But regenerating this does not guarantee it will compile or work if glibc 2.34 made significant changes to the interface.

**Comment by frenkel** [comment]
Thanks! Unfortunately that doesn't help for glibc 2.34. I used your instructions to regenerate the `libresol-sys/lib.rs` file and had to make two changes in `src/lib.rs` to get it working with glibc 2.34: https://github.com/frenkel/resolv-rs/tree/glibc234

If I understand it correctly it will be a major pain to support both glibc versions. What would be the best way forward?

**Comment by mikedilger** [comment]
Sorry for the delay things got really busy here.

I think we just keep upgrading to new versions of glibc, and if people need the old versions they can fix the version number in cargo.  If new features were being developed, we'd want to leave version number space for point releases on the old versions.

Arch is still on 2.33-5 so I can't develop for 2.34 yet.  But if you do a PR with your changes I'll keep it in-the-ready on a separate branch, and I guess you can refer to that branch in your project for now (or to your own local copy).

**Comment by frenkel** [comment]
Sounds good. I only seem to be able to create a pull request to master or other existing branches. Could you create a branch so I can open a pull request?

**Comment by mikedilger** [comment]
Ok I created glibc234 branch.

**Comment by frenkel** [comment]
Great! See: https://github.com/mikedilger/resolv-rs/pull/6

**Comment by frenkel** [comment]
I see quite some changes regarding this have made it into master. They work great on my builders! Would you be able to publish a new release on crates.io?

**Comment by mikedilger** [comment]
Good idea.

I've pushed version 0.3.0 for both libresolv-sys (with the major new way of building) and resolv that depends on it

**Comment by frenkel** [comment]
Great, thanks!
